site_name: Solital Framework 
nav:
  - Starting: index.md
  - Upgrade: 
    - Release Notes: release-notes.md
    - Upgrade Guide: upgrade-guide.md
  - Settings:
    - Installing: installation.md
    - Environment Variables: environment-variables.md
    - YAML Files: yaml-files.md
    - Helpers: helpers.md
  - Routers:
    - Routes: routes.md
    - Middleware: middleware.md
    - URL: url.md
    - Events: events.md
    - Input and params: input-and-params.md
  - Components:
    - Vinci Console: vinci-console.md
    - Cache: cache.md
    - Dependency Container : dependency-container.md
    - HTTP Client: http-client.md
    - Wolf Template: wolf-template.md
  - Resources:
    - Date and time: date-and-time.md
    - File System: file-system.md
    - JSON: json.md
    - Logger: logger.md
    - Mailer: mailer-component.md
    - Session and Cookie: session-and-cookie.md
    - Validation: validation-component.md
    - Messages: messages.md
    - Queue: queue.md
    - Collection: collection.md
    - Strings: string-manipulate.md
    - Mask: mask.md
  - Security:
    - Authenticate: authenticate.md
    - Cryptography: cryptography.md
    - CSRF Protection: csrf-protection.md
    - Secure Password: secure-password.md
    - Verify Domain: verify-domain.md
    - Recovery Password: recovery-password.md
  - Database:
    - Migrations: migrations.md
    - Seeders: seeders.md
    - Dump: dump.md
    - Katrina ORM: katrina-orm.md
  - Deploy: deploy.md
theme:
    name: null
    custom_dir: basic_theme/
plugins:
    - search