site_name: Solital Framework 
nav:
  - Starting: index.md
  - Upgrade: 
    - Release Notes: https://github.com/solital/core/releases
    - Upgrade Guide: upgrade-guide.md
  - Settings:
    - Environment Variables: environment-variables.md
    - YAML Files: yaml-files.md
    - Helpers: helpers.md
    - Exceptions: exceptions.md
    - API Application: application-api.md
  - Routers:
    - Routes: routes.md
    - Middleware: middleware.md
    - URL: url.md
    - Events: events.md
    - Input and params: input-and-params.md
  - Components:
    - Vinci Console: vinci-console.md
    - Cache: cache.md
    - Controllers and Models: controller-model.md
    - Date and time: date-and-time.md
    - Dependency Container : dependency-container.md
    - Event Loop: event-loop.md
    - HTTP Client: http-client.md
    - Mailer: mailer-component.md
    - Task Schedule: schedule.md
    - Wolf Template: wolf-template.md
  - Resources:
    - Browser Storage: browser-storage.md
    - Cookie: cookie.md
    - Collection: collection.md
    - File System: file-system.md
    - JSON: json.md
    - Logger: logger.md
    - Messages: messages.md
    - Number: number.md
    - Queue: queue.md
    - Session: session.md
    - Strings: string-manipulate.md
    - Validation: validation.md
    - Mask: mask.md
  - Security:
    - Authenticate: authenticate.md
    - Authorization: authorization.md
    - Cryptography: cryptography.md
    - CSRF Protection: csrf-protection.md
    - Secure Password: secure-password.md
    - Verify Domain: verify-domain.md
    - Recovery Password: recovery-password.md
    - Malware Scanner: scanner.md
  - Database:
    - Migrations: migrations.md
    - Seeders: seeders.md
    - Dump: dump.md
    - Katrina ORM: katrina-orm.md
  - Deploy: deploy.md
theme:
    name: null
    custom_dir: solital_docs_theme/
plugins:
    - search